/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.bmi;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int height=0x7f040000;
        public static final int result=0x7f040003;
        public static final int submit=0x7f040002;
        public static final int suggest=0x7f040004;
        public static final int weight=0x7f040001;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int advice_average=0x7f030006;
        public static final int advice_heavy=0x7f030007;
        public static final int advice_light=0x7f030005;
        public static final int app_name=0x7f030000;
        public static final int bmi_error=0x7f030008;
        public static final int bmi_result=0x7f030004;
        public static final int your_count=0x7f030003;
        public static final int your_height=0x7f030001;
        public static final int your_weight=0x7f030002;
    }
}
